export const leadershipTeam = [
  {
    name: "Rajsinh Phadtare",
    role: "CEO",
    bio: "Leading Innvikta’s vision for human risk reduction and enterprise security awareness.",
    image: "/images/about/team/raj.png",
    summary: "Visionary leader driving Innvikta's mission to eliminate the human recall gap in enterprise cybersecurity.",
    longBio: "Rajsinh has dedicated his career to designing human-centric security programs that convert technical compliance requirements into measurable habits. Under his leadership, Innvikta has scaled to serve enterprises globally, focusing on AI-driven awareness campaigns and realistic multi-channel phishing simulations.",
    quote: "Human risk is not a technology challenge. It is a behavior challenge that requires behavioral solutions.",
    expertise: ["Cybersecurity", "Human Risk", "Governance", "Enterprise Strategy", "Compliance", "Business Growth"],
    linkedin: "https://linkedin.com",
  },
  {
    name: "Nakul Ilawe",
    role: "CMO & Growth Lead",
    bio: "Driving market strategy, partnerships, customer engagement, and brand growth.",
    image: "/images/about/team/nakul.png",
    summary: "Growth strategist aligning product capability with enterprise market needs and strategic partnerships.",
    longBio: "Nakul directs Innvikta’s go-to-market execution, driving brand engagement and scaling enterprise adoption. He specializes in designing user-focused security education programs that resonate with modern workforces and deliver clear business outcomes.",
    quote: "Security is only effective when it becomes a natural, friction-free part of the employee's daily workflow.",
    expertise: ["Growth Strategy", "Product Marketing", "Partnerships", "Brand Development", "Customer Experience"],
    linkedin: "https://linkedin.com",
  },
  {
    name: "Dnyaneshwar Phadtare (IPS retd.)",
    role: "Board Advisor",
    bio: "Guiding cybersecurity strategy and risk readiness based on real-world security and public-sector insight.",
    image: "/images/about/team/Dnyaneshwar.png",
    summary: "Distinguished security expert advising on strategic threat landscapes, public sector compliance, and risk readiness.",
    longBio: "With a highly distinguished career in public service and law enforcement, Dnyaneshwar brings invaluable strategic insights to Innvikta. He advises on emerging cyber threat vectors, state-level compliance mandates, and organizational security resilience.",
    quote: "True defense lies in empowering the individual. Technology changes, but human nature remains the constant.",
    expertise: ["Threat Intelligence", "Public Policy", "Risk Readiness", "Strategic Security", "Incident Response"],
    linkedin: "https://linkedin.com",
  },
  {
    name: "Santosh Kamane",
    role: "Board Advisor",
    bio: "Advising on business direction, growth, partnerships, and organizational impact.",
    image: "/images/about/team/santosh.png",
    summary: "Enterprise strategy expert guiding business development, scale initiatives, and corporate governance.",
    longBio: "Santosh works closely with the executive team to define corporate strategy, structure joint ventures, and govern commercial expansion. His extensive enterprise background guides Innvikta's partnerships and growth acceleration.",
    quote: "Scaling a business requires alignment of vision, flawless operational execution, and trust.",
    expertise: ["Corporate Governance", "M&A", "Commercial Scale", "Business Operations", "Strategic Partnerships"],
    linkedin: "https://linkedin.com",
  },
];
